name: Push to Another Repository

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때 이 워크플로우가 실행됩니다. 필요에 따라 브랜치를 변경할 수 있습니다.

jobs:
  push_to_other_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Push to another repository
        run: |
          git remote add other-repo https://github.com/univ3-react-study/react_study_univ3.git
          git push other-repo main
        # env:
        #   USERNAME: ${{ secrets.USERNAME }}  # GitHub 비밀변수에 설정된 사용자 이름
        #   TOKEN: ${{ secrets.TOKEN }}        # GitHub 비밀변수에 설정된 토큰
